"""Identity-checked shutdown helper shared by the Windows pet installers."""

from __future__ import annotations

import subprocess
from collections.abc import Callable
from pathlib import Path

STOP_PROXY_PS1 = r"""$ErrorActionPreference = 'Stop'
$ExpectedExe = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot 'roleplay-slim-proxy.exe'))
$ExpectedConfig = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot 'config.toml'))
$Connection = Get-NetTCPConnection -LocalPort {port} -State Listen -ErrorAction SilentlyContinue |
    Select-Object -First 1

if ($null -eq $Connection) {{
    Write-Output 'NOT_RUNNING'
    exit 0
}}

$Process = Get-CimInstance Win32_Process -Filter ("ProcessId = " + $Connection.OwningProcess)
$ActualExe = if ($Process.ExecutablePath) {{
    [System.IO.Path]::GetFullPath($Process.ExecutablePath)
}} else {{
    ''
}}
$HasExpectedConfig = $Process.CommandLine -and (
    $Process.CommandLine.IndexOf($ExpectedConfig, [System.StringComparison]::OrdinalIgnoreCase) -ge 0
)

if (
    -not $ActualExe.Equals($ExpectedExe, [System.StringComparison]::OrdinalIgnoreCase) -or
    -not $HasExpectedConfig
) {{
    Write-Output 'REFUSED_FOREIGN_PROCESS'
    exit 2
}}

Stop-Process -Id $Connection.OwningProcess -Force -ErrorAction Stop
Write-Output 'STOPPED'
"""


def write_stop_script(config_dir: Path, port: int) -> Path:
    path = config_dir / "stop_proxy.ps1"
    path.write_text(STOP_PROXY_PS1.format(port=port), encoding="utf-8")
    return path


def stop_installed_proxy(
    pet_dir: Path,
    port: int = 8791,
    *,
    runner: Callable[..., subprocess.CompletedProcess[str]] = subprocess.run,
) -> bool:
    """Run only the exact stop script generated by this version."""
    script = pet_dir / "roleplay-slim-proxy" / "stop_proxy.ps1"
    expected = STOP_PROXY_PS1.format(port=port)
    try:
        if script.read_text(encoding="utf-8-sig") != expected:
            return False
    except (OSError, UnicodeError):
        return False

    result = runner(
        [
            "powershell",
            "-NoProfile",
            "-ExecutionPolicy",
            "Bypass",
            "-File",
            str(script),
        ],
        capture_output=True,
        text=True,
        timeout=10,
        check=False,
    )
    return result.returncode == 0 and result.stdout.strip() == "STOPPED"
