"""
roleplay-slim installer core for Cyrene-Agent (Electron desktop pet,
https://github.com/Playa-0v0/Cyrene-Agent).

Unlike BandoriPet (a plain string literal baked into index.html), Cyrene
already exposes an official, user-editable LLM endpoint: a JSON file at
``%APPDATA%\\live2d-cyrene\\model-settings.json`` with a ``baseUrl`` field
per provider, resolved at request time via a lenient URL-suffix rule (any
value not already ending in ``/chat/completions`` gets it appended). So
this is a JSON field edit, not a text patch — no `old`/`new` string pair,
no length constraint, no risk of "pattern not found because this version's
layout differs" the way BandoriPet has two known layouts.

Cyrene's own renderer sends its own ``Authorization: Bearer <apiKey>``
header on every request (the ``apiKey`` field already sitting in
model-settings.json). The proxy forwards a caller-supplied Authorization
header through to the real upstream unchanged (same
incoming-auth-wins-over-configured-key behavior verified for BandoriPet in
roleplay_slim.proxy.server) — so, same as BandoriPet, there is no API key
for this installer to read, store, or configure. It only ever touches the
URL.

Cyrene's own system prompt (``prompts/chat_system.md`` in a real install)
explicitly forbids the model from wrapping actions/expressions in
parentheses/asterisks — the opposite convention from Mutsumi/BandoriPet.
So ``enable_strip_stage_directions`` stays off here: there is no
stage-direction text of that shape for this app to ever produce, not just
an unconfirmed guess.

Usage:
    python patch_cyrene.py                 # auto-detect from script location
    python patch_cyrene.py "D:\\Cyrene1"    # explicit Cyrene install directory
"""

import json
import os
import shutil
import sys
from pathlib import Path

_PET_INSTALLER_DIR = Path(__file__).resolve().parents[1]
if str(_PET_INSTALLER_DIR) not in sys.path:
    sys.path.insert(0, str(_PET_INSTALLER_DIR))

from safe_process import write_stop_script  # noqa: E402

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
PROXY_PORT = 8793  # 8791 = Mutsumi, 8792 = BandoriPet — each pet gets its own
                    # port so more than one can run its own proxy at once.

BACKUP_SUFFIX = ".roleplay-slim.bak"

DEFAULT_PROVIDER = "DeepSeek（深度求索）"
DEFAULT_MODEL = "deepseek-v4-flash"

CONFIG_TOML = """# roleplay-slim proxy config for Cyrene-Agent
# Auto-generated by installer — edit at your own risk.

[proxy]
upstream_base_url = "https://api.deepseek.com/v1"
upstream_api_key_env = "UPSTREAM_API_KEY"
host = "127.0.0.1"
port = {port}

[compressor]
keep_recent_turns = 6
enable_whitespace_normalize = true
enable_dedupe_verbatim_tail = true
enable_history_window = true
enable_strip_stage_directions = false
history_window_mode = "trim"
"""

LAUNCH_PROXY_BAT = """@echo off
title roleplay-slim-proxy-cyrene
cd /d "%~dp0"
"%~dp0roleplay-slim-proxy\\roleplay-slim-proxy.exe" --config "%~dp0roleplay-slim-proxy\\config.toml"
"""

LAUNCH_PET_BAT = r"""@echo off
if /I "%~1"=="min" goto :main
start "" /min cmd /c "%~f0" min
exit /b

:main
cd /d "%~dp0"

echo =====================================
echo   Cyrene — 正在启动...
echo =====================================

echo [1/3] 启动上下文代理...
start "roleplay-slim-proxy-cyrene" /min cmd /c "%CD%\启动代理.bat"

echo [2/3] 等待代理就绪...
powershell -Command ^"$i=0; while($i -lt 30){try{$r=Invoke-WebRequest 'http://127.0.0.1:{port}/healthz' -TimeoutSec 1 -UseBasicParsing;if($r.StatusCode -eq 200){exit 0}}catch{}$i++;Start-Sleep 1};exit 1^"
if errorlevel 1 (
    echo [错误] 代理启动超时，请关闭杀毒软件后重试
    powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0roleplay-slim-proxy\stop_proxy.ps1" >nul 2>&1
    pause
    exit /b 1
)

echo [3/3] 启动 Cyrene...
start "" /wait "Cyrene.exe"

echo Cyrene 已关闭，停止代理...
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0roleplay-slim-proxy\stop_proxy.ps1" >nul 2>&1

exit
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def find_model_settings_path() -> Path:
    """Cyrene's model-settings.json lives in the Electron userData folder,
    not inside the install directory — fixed location, no install-dir
    argument needed to find it."""
    appdata = os.environ.get("APPDATA")
    if not appdata:
        raise FileNotFoundError("APPDATA 环境变量未设置，无法定位 Cyrene 的用户数据目录")
    path = Path(appdata) / "live2d-cyrene" / "model-settings.json"
    if not path.parent.is_dir():
        raise FileNotFoundError(
            f"{path.parent} 不存在 —— Cyrene 是否至少启动运行过一次？"
        )
    return path


def find_cyrene_exe(pet_dir: Path) -> Path | None:
    candidate = pet_dir / "Cyrene.exe"
    return candidate if candidate.is_file() else None


def _proxy_base_url(port: int) -> str:
    return f"http://127.0.0.1:{port}/v1"


def patch_model_settings(settings_path: Path, port: int, log=None) -> bool | None:
    """Point the current provider's baseUrl at the local proxy.

    Returns:
        True  — patched just now
        False — already patched (idempotent no-op)
        None  — file didn't exist yet; a fresh default DeepSeek profile was
                created instead (apiKey left blank — this installer never
                asks for or stores the real key, same as BandoriPet's).
    """
    if log is None:
        log = print

    proxy_base = _proxy_base_url(port)

    if not settings_path.is_file():
        data = {
            "mode": "manual",
            "provider": DEFAULT_PROVIDER,
            "baseUrl": proxy_base,
            "model": DEFAULT_MODEL,
            "apiKey": "",
            "explicitTransport": "openai",
            "perProvider": {
                DEFAULT_PROVIDER: {
                    "baseUrl": proxy_base,
                    "model": DEFAULT_MODEL,
                    "apiKey": "",
                    "explicitTransport": "openai",
                }
            },
        }
        settings_path.write_text(
            json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        log(
            "  [info] model-settings.json 不存在，已创建默认 DeepSeek 配置"
            "（API Key 留空 —— 请在 Cyrene 设置页面里自己填，安装器不读取也不存储真实 key）"
        )
        return None

    data = json.loads(settings_path.read_text(encoding="utf-8"))
    provider = data.get("provider") or DEFAULT_PROVIDER
    current_base = data.get("baseUrl", "")
    per_provider = data.setdefault("perProvider", {})
    profile = per_provider.setdefault(provider, {})
    current_transport = data.get("explicitTransport") or profile.get("explicitTransport")

    already_routed = current_base.startswith(f"http://127.0.0.1:{port}")
    if already_routed and current_transport == "openai":
        log(f"  [info] baseUrl 已指向本地代理且 transport 已是 openai，跳过")
        return False

    data["baseUrl"] = proxy_base
    profile["baseUrl"] = proxy_base
    # model/apiKey are preserved untouched, but the transport is FORCED to
    # openai rather than left alone: roleplay-slim only understands
    # /v1/chat/completions (it does no Anthropic↔OpenAI translation). An
    # existing profile that kept Cyrene's DeepSeek-preset "anthropic"
    # transport would keep sending /v1/messages, which the proxy forwards to
    # a nonexistent upstream path and the provider rejects with 401 (the
    # exact failure the frozen installer hit on a second machine).
    profile.setdefault("model", data.get("model", DEFAULT_MODEL))
    profile.setdefault("apiKey", data.get("apiKey", ""))
    profile["explicitTransport"] = "openai"
    data["explicitTransport"] = "openai"

    tmp_path = settings_path.with_name("_" + settings_path.name + ".tmp")
    tmp_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    os.replace(str(tmp_path), str(settings_path))
    log(f"  [OK] model-settings.json: {provider} 的 baseUrl → {proxy_base}")
    return True


def uninstall_cyrene(pet_dir: Path, log=None) -> None:
    """Restore model-settings.json from its backup and remove every file
    the installer added. Backups themselves are never deleted."""
    if log is None:
        log = print

    log("正在还原配置文件...")
    try:
        settings_path = find_model_settings_path()
        backup = settings_path.with_name(settings_path.name + BACKUP_SUFFIX)
        if backup.is_file():
            shutil.copy2(backup, settings_path)
            log("  [OK] model-settings.json 已还原")
        else:
            log("  [info] 备份不存在，跳过（如果安装时是全新创建的，直接删除即可）")
    except FileNotFoundError as e:
        log(f"  [warn] {e}")

    log("")
    log("正在清理代理文件...")
    for name in ("启动代理.bat", "Cyrene启动.bat"):
        p = pet_dir / name
        if p.exists():
            p.unlink()
            log(f"  [OK] 已删除: {name}")

    proxy_dir = pet_dir / "roleplay-slim-proxy"
    if proxy_dir.is_dir():
        shutil.rmtree(proxy_dir)
        log("  [OK] 已删除: roleplay-slim-proxy\\")

    log("")
    log("还原完成！Cyrene 已恢复到安装前的状态。")


# ---------------------------------------------------------------------------
# Main (CLI, mirrors installer_bandori/patch_bandori.py's structure)
# ---------------------------------------------------------------------------
def main() -> None:
    print("=" * 60)
    print("  Cyrene-Agent — roleplay-slim 上下文优化安装工具")
    print("=" * 60)
    print()

    if len(sys.argv) > 1:
        pet_dir = Path(sys.argv[1]).resolve()
    else:
        script_dir = Path(__file__).resolve().parent
        pet_dir = script_dir.parent if (script_dir.parent / "Cyrene.exe").is_file() else Path.cwd()

    print(f"[*] Cyrene 安装目录: {pet_dir}")
    if not pet_dir.is_dir():
        print(f"[错误] 目录不存在: {pet_dir}")
        sys.exit(1)

    print("\n[1/4] 查找关键文件...")
    exe = find_cyrene_exe(pet_dir)
    if exe:
        print(f"  [OK] Cyrene.exe: {exe}")
    else:
        print(f"  [警告] 未在此目录找到 Cyrene.exe —— 启动脚本仍会生成，但请确认目录正确")

    try:
        settings_path = find_model_settings_path()
        print(f"  [OK] model-settings.json 位置: {settings_path}")
    except FileNotFoundError as e:
        print(f"  [错误] {e}")
        sys.exit(1)

    print("\n[2/4] 备份配置文件...")
    if settings_path.is_file():
        backup = settings_path.with_name(settings_path.name + BACKUP_SUFFIX)
        if not backup.exists():
            shutil.copy2(settings_path, backup)
            print("  [OK] model-settings.json 已备份")
        else:
            print("  [info] 备份已存在")
    else:
        print("  [info] model-settings.json 尚不存在，跳过备份（安装时会创建默认配置）")

    print("\n[3/4] 修改模型配置...")
    patch_model_settings(settings_path, PROXY_PORT)

    print("\n[4/4] 生成代理配置与启动脚本...")
    config_dir = pet_dir / "roleplay-slim-proxy"
    config_dir.mkdir(exist_ok=True)
    (config_dir / "config.toml").write_text(
        CONFIG_TOML.format(port=PROXY_PORT), encoding="utf-8"
    )
    write_stop_script(config_dir, PROXY_PORT)
    print("  [OK] config.toml 写入")

    (pet_dir / "启动代理.bat").write_text(LAUNCH_PROXY_BAT, encoding="gbk")
    (pet_dir / "Cyrene启动.bat").write_text(
        LAUNCH_PET_BAT.replace("{port}", str(PROXY_PORT)), encoding="gbk"
    )
    print("  [OK] 启动代理.bat / Cyrene启动.bat")

    print("\n" + "=" * 60)
    print("  安装完成！以后双击「Cyrene启动.bat」启动即可")
    print("=" * 60)


if __name__ == "__main__":
    main()
