"""
roleplay-slim installer core for BandoriPet Voice Append (Electron desktop pet).

Unlike the Mutsumi pet (compiled Unity binary, byte-precise same-length
patching required), BandoriPet's chat request URL lives as a plain string
literal inside index.html (renderer JS) — a normal text file, so this is a
simple str.replace(), no length constraints.

The renderer sends its own ``Authorization: Bearer <key>`` header on every
request. The proxy forwards that header through to the real upstream
unchanged (see roleplay_slim.proxy.server: incoming_auth takes priority over
the proxy's own configured key), so there is no API key to read or configure
here at all — only the URL needs to change.

Usage:
    python patch_bandori.py          # auto-detect from script location
    python patch_bandori.py "E:\\...\\win-unpacked"   # explicit path
"""

import os
import sys
import shutil
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
DEEPSEEK_CHAT_URL = "https://api.deepseek.com/v1/chat/completions"
DEEPSEEK_BASE_URL = "https://api.deepseek.com/v1"

PROXY_PORT = 8792  # different from the Mutsumi proxy's 8791, so both pets
                    # can run their own proxy at the same time without a
                    # port clash.

BACKUP_SUFFIX = ".roleplay-slim.bak"  # namespaced so it never collides with
                                       # this app's own memory/backup patches
                                       # (which use "*.bak-yyyymmdd-HHmmss"
                                       # and "backups/<iso-timestamp>/..." )

CONFIG_TOML = """# roleplay-slim proxy config for BandoriPet Voice Append
# Auto-generated by installer — edit at your own risk.

[proxy]
upstream_base_url = "https://api.deepseek.com/v1"
upstream_api_key_env = "UPSTREAM_API_KEY"
host = "127.0.0.1"
port = {port}

[compressor]
keep_recent_turns = 4
enable_whitespace_normalize = true
enable_dedupe_verbatim_tail = true
enable_history_window = true
enable_strip_stage_directions = true
history_window_mode = "trim"
stage_direction_pattern = "fullwidth_parens"
"""

LAUNCH_PROXY_BAT = """@echo off
title roleplay-slim-proxy-bandori
cd /d "%~dp0"
"%~dp0roleplay-slim-proxy\\roleplay-slim-proxy.exe" --config "%~dp0roleplay-slim-proxy\\config.toml"
"""

LAUNCH_PET_BAT = r"""@echo off
:: Relaunch this script minimized on the first run — no Add-Type/dynamic
:: code compilation involved (that approach printed a stray "False" from
:: ShowWindow's return value and wasn't reliable under a standard user
:: account). The tradeoff is "minimized" instead of "fully hidden", but
:: it's a plain batch trick with nothing that can silently fail.
if /I "%~1"=="min" goto :main
start "" /min cmd /c "%~f0" min
exit /b

:main
cd /d "%~dp0"

echo =====================================
echo   BandoriPet — 正在启动...
echo =====================================

echo [1/3] 启动上下文代理...
start "roleplay-slim-proxy-bandori" /min cmd /c "%CD%\启动代理.bat"

echo [2/3] 等待代理就绪...
powershell -Command ^"$i=0; while($i -lt 30){try{$r=Invoke-WebRequest 'http://127.0.0.1:{port}/healthz' -TimeoutSec 1 -UseBasicParsing;if($r.StatusCode -eq 200){exit 0}}catch{}$i++;Start-Sleep 1};exit 1^"
if errorlevel 1 (
    echo [错误] 代理启动超时，请关闭杀毒软件后重试
    taskkill /fi "WINDOWTITLE eq roleplay-slim-proxy-bandori*" /f >nul 2>&1
    pause
    exit /b 1
)

echo [3/3] 启动桌宠...
start "" /wait "BandoriPet Voice Append.exe"

echo 桌宠已关闭，停止代理...
powershell -Command ^"try{$c=Get-NetTCPConnection -LocalPort {port} -ErrorAction Stop;Stop-Process -Id $c.OwningProcess -Force -ErrorAction Stop}catch{}^"

exit
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def find_index_html(pet_dir: Path) -> Path:
    """Find index.html in the Electron app's resources folder."""
    candidate = pet_dir / "resources" / "app" / "index.html"
    if candidate.is_file():
        return candidate
    raise FileNotFoundError(
        f"index.html not found in {pet_dir}\\resources\\app\\. "
        "Is this the correct win-unpacked directory?"
    )


def find_ai_config(pet_dir: Path) -> Path | None:
    """Find ai_config.json — optional, best-effort consistency patch only."""
    candidate = pet_dir / "resources" / "app" / "ai_config.json"
    return candidate if candidate.is_file() else None


def find_pet_exe(pet_dir: Path) -> Path | None:
    """Find the main BandoriPet executable at the install root."""
    for c in pet_dir.glob("BandoriPet*.exe"):
        return c
    return None


def patch_text_file(file_path: Path, old: str, new: str, log=None) -> bool | None:
    """Replace ALL occurrences of `old` with `new` in a plain text file.

    No length constraint here (unlike the Mutsumi Unity patch) — this is
    ordinary source text, not a compiled binary with fixed string-table
    offsets.

    BandoriPet ships in at least two different code layouts depending on
    whether the "long-term memory" community patch is installed: the
    patched layout hardcodes the DeepSeek URL directly in index.html, while
    the stock/official layout routes chat through main.js's IPC handler
    into services/aiService.js, which reads ai_config.json instead — that
    layout has no matching string in index.html at all. Neither is wrong,
    they're just different files depending on version, so "pattern not
    found" is not automatically fatal for any *single* file — the caller
    decides what to do across the full set of candidate files.

    Returns:
        True  — patched just now
        False — already patched (idempotent no-op)
        None  — neither `old` nor `new` present; this file doesn't use
                this configuration mechanism in this version at all
    """
    if log is None:
        log = print
    text = file_path.read_text(encoding="utf-8")

    count = text.count(old)
    if count == 0:
        if new in text:
            log(f"  [info] {file_path.name} 已经是最新状态 — 跳过")
            return False
        log(f"  [info] {file_path.name} 中未找到目标字符串 — 该文件可能不是这个版本的实际配置来源")
        return None

    new_text = text.replace(old, new)

    tmp_path = file_path.with_name("_" + file_path.name + ".tmp")
    tmp_path.write_text(new_text, encoding="utf-8")
    os.replace(str(tmp_path), str(file_path))
    log(f"  [OK] {file_path.name}: 替换了 {count} 处")
    return True


def uninstall_bandori(pet_dir: Path, log=None) -> None:
    """Restore index.html / ai_config.json from their backups and remove
    every file the installer added. Backups themselves are never deleted."""
    if log is None:
        log = print

    log("正在还原游戏文件...")

    try:
        index_path = find_index_html(pet_dir)
        backup = index_path.with_name(index_path.name + BACKUP_SUFFIX)
        if backup.is_file():
            shutil.copy2(backup, index_path)
            log(f"  [OK] index.html 已还原")
        else:
            log(f"  [info] index.html 备份不存在，跳过")
    except FileNotFoundError:
        log(f"  [warn] 未找到 index.html，跳过")

    ai_config = find_ai_config(pet_dir)
    if ai_config:
        backup = ai_config.with_name(ai_config.name + BACKUP_SUFFIX)
        if backup.is_file():
            shutil.copy2(backup, ai_config)
            log(f"  [OK] ai_config.json 已还原")
        else:
            log(f"  [info] ai_config.json 备份不存在，跳过")

    log("")
    log("正在清理代理文件...")
    for name in ("启动代理.bat", "若叶睦.bat", "BandoriPet.bat"):
        p = pet_dir / name
        if p.exists():
            p.unlink()
            log(f"  [OK] 已删除: {name}")

    proxy_dir = pet_dir / "roleplay-slim-proxy"
    if proxy_dir.is_dir():
        shutil.rmtree(proxy_dir)
        log(f"  [OK] 已删除: roleplay-slim-proxy\\")

    log("")
    log("还原完成！桌宠已恢复到安装前的状态。")


# ---------------------------------------------------------------------------
# Main (CLI, mirrors installer/install.py's structure for dev use)
# ---------------------------------------------------------------------------
def main() -> None:
    print("=" * 60)
    print("  BandoriPet — roleplay-slim 上下文优化安装工具")
    print("=" * 60)
    print()

    if len(sys.argv) > 1:
        pet_dir = Path(sys.argv[1]).resolve()
    else:
        script_dir = Path(__file__).resolve().parent
        pet_dir = script_dir.parent if (script_dir.parent / "resources" / "app").is_dir() else Path.cwd()

    print(f"[*] 桌宠目录: {pet_dir}")
    if not pet_dir.is_dir():
        print(f"[错误] 目录不存在: {pet_dir}")
        sys.exit(1)

    print("\n[1/5] 查找关键文件...")
    try:
        index_path = find_index_html(pet_dir)
        print(f"  [OK] index.html: {index_path}")
    except FileNotFoundError as e:
        print(f"  [错误] {e}")
        sys.exit(1)

    ai_config = find_ai_config(pet_dir)
    if ai_config:
        print(f"  [OK] ai_config.json: {ai_config}")

    print("\n[2/5] 备份原文件...")
    backup = index_path.with_name(index_path.name + BACKUP_SUFFIX)
    if not backup.exists():
        shutil.copy2(index_path, backup)
        print(f"  [OK] index.html 已备份")
    else:
        print(f"  [info] 备份已存在")

    if ai_config:
        ai_backup = ai_config.with_name(ai_config.name + BACKUP_SUFFIX)
        if not ai_backup.exists():
            shutil.copy2(ai_config, ai_backup)
            print(f"  [OK] ai_config.json 已备份")

    print(f"\n[3/5] Patch index.html (硬编码版本才有此字符串)...")
    proxy_url = f"http://127.0.0.1:{PROXY_PORT}/v1/chat/completions"
    index_result = patch_text_file(index_path, DEEPSEEK_CHAT_URL, proxy_url)

    ai_config_result = None
    if ai_config:
        print(f"\n[3.5/5] Patch ai_config.json (官方原版走这条路径)...")
        proxy_base = f"http://127.0.0.1:{PROXY_PORT}/v1"
        ai_config_result = patch_text_file(ai_config, DEEPSEEK_BASE_URL, proxy_base)

    # Only a real failure if NEITHER known configuration mechanism matched —
    # one of them not matching just means this version uses the other one.
    if index_result is None and ai_config_result is None:
        print("  [错误] index.html 和 ai_config.json 都未找到匹配的 DeepSeek URL。")
        print("  这个版本可能既不是记忆补丁版本也不是已知的官方版本，需要人工排查。")
        sys.exit(1)

    print(f"\n[4/5] 生成代理配置...")
    config_dir = pet_dir / "roleplay-slim-proxy"
    config_dir.mkdir(exist_ok=True)
    (config_dir / "config.toml").write_text(
        CONFIG_TOML.format(port=PROXY_PORT), encoding="utf-8"
    )
    print(f"  [OK] config.toml 写入")

    print(f"\n[5/5] 创建启动脚本...")
    (pet_dir / "启动代理.bat").write_text(LAUNCH_PROXY_BAT, encoding="gbk")
    (pet_dir / "BandoriPet.bat").write_text(
        LAUNCH_PET_BAT.replace("{port}", str(PROXY_PORT)), encoding="gbk"
    )
    print(f"  [OK] 启动代理.bat / BandoriPet.bat")

    print("\n" + "=" * 60)
    print("  安装完成！以后双击「BandoriPet.bat」启动即可")
    print("=" * 60)


if __name__ == "__main__":
    main()
