"""
roleplay-slim installer for Mutsumi Desktop Pet (若叶睦桌宠).

Run once, then forget. Patches the game's API endpoint to route through a
local compression proxy. No configuration needed by the end user.

Usage:
    python install.py          # auto-detect pet directory from script location
    python install.py E:\壁纸\若叶睦桌宠\小睦1.9.0   # explicit path
"""

import os
import sys
import shutil
import struct
import winreg
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
DEEPSEEK_URL = b"https://api.deepseek.com/chat/completions"
PROXY_URL = b"http://127.0.0.1:8791/v1/chat/completions"

assert len(DEEPSEEK_URL) == len(PROXY_URL), (
    f"URL lengths must match: {len(DEEPSEEK_URL)} vs {len(PROXY_URL)}"
)

REG_PATH = r"Software\孤独摇摆阳\若叶睦桌宠"
REG_KEY = "DeepSeek_API_Key"  # prefix match — Unity appends hash suffix

# Newer pet builds (1.9.5+) add a dynamic API URL PlayerPrefs setting that
# overrides the binary's compiled-in default at runtime — the binary patch
# alone silently does nothing on those versions since this value wins.
# Older builds (e.g. 1.9.0) never had this setting at all; on those,
# find_registry_url_entry() finds nothing and the binary patch is fully
# sufficient by itself.
REG_URL_KEY = "LlmApiUrl"
REG_BACKUP_SUFFIX = "_roleplay_slim_bak"

PROXY_PORT = 8791

CONFIG_TOML = """# roleplay-slim proxy config for Mutsumi Desktop Pet
# Auto-generated by installer — edit at your own risk.

[proxy]
upstream_base_url = "https://api.deepseek.com/v1"
upstream_api_key_env = "UPSTREAM_API_KEY"
host = "127.0.0.1"
port = {port}

[compressor]
keep_recent_turns = 4
enable_whitespace_normalize = true
enable_dedupe_verbatim_tail = true
enable_history_window = true
enable_strip_stage_directions = true
history_window_mode = "trim"
stage_direction_pattern = "fullwidth_parens"
"""

LAUNCH_PROXY_BAT = """@echo off
set "UPSTREAM_API_KEY={api_key}"
title roleplay-slim-proxy
cd /d "%~dp0"
"%~dp0roleplay-slim-proxy\\roleplay-slim-proxy.exe" --config "%~dp0roleplay-slim-proxy\\config.toml"
"""

LAUNCH_PET_BAT = r"""@echo off
:: Relaunch this script minimized on the first run — no Add-Type/dynamic
:: code compilation involved (that approach printed a stray "False" from
:: ShowWindow's return value and wasn't reliable under a standard user
:: account). The tradeoff is "minimized" instead of "fully hidden", but
:: it's a plain batch trick with nothing that can silently fail.
if /I "%~1"=="min" goto :main
start "" /min cmd /c "%~f0" min
exit /b

:main
cd /d "%~dp0"

echo =====================================
echo   若叶睦 — 正在启动...
echo =====================================

:: Start proxy in background (minimized window)
echo [1/3] 启动上下文代理...
start "roleplay-slim-proxy" /min cmd /c "%CD%\启动代理.bat"

:: Wait for proxy to be ready (powershell health check, max 30 attempts)
echo [2/3] 等待代理就绪...
powershell -Command ^"$i=0; while($i -lt 30){try{$r=Invoke-WebRequest 'http://127.0.0.1:{port}/healthz' -TimeoutSec 1 -UseBasicParsing;if($r.StatusCode -eq 200){exit 0}}catch{}$i++;Start-Sleep 1};exit 1^"
if errorlevel 1 (
    echo [错误] 代理启动超时，请关闭杀毒软件后重试
    taskkill /fi "WINDOWTITLE eq roleplay-slim-proxy*" /f >nul 2>&1
    pause
    exit /b 1
)

:: Launch the desktop pet
echo [3/3] 启动桌宠...
start "" /wait "若叶睦桌宠.exe"

:: Pet closed — shut down proxy
echo 桌宠已关闭，停止代理...
powershell -Command ^"try{$c=Get-NetTCPConnection -LocalPort {port} -ErrorAction Stop;Stop-Process -Id $c.OwningProcess -Force -ErrorAction Stop}catch{}^"

exit
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def find_level0(pet_dir: Path) -> Path:
    """Find level0 in the desktop pet directory."""
    candidates = [
        pet_dir / "若叶睦桌宠_Data" / "level0",
        pet_dir / "若叶睦桌寵_Data" / "level0",
    ]
    for c in candidates:
        if c.is_file():
            return c
    # Search recursively (but only one level deep)
    for child in pet_dir.iterdir():
        if child.is_dir():
            l0 = child / "level0"
            if l0.is_file():
                return l0
    raise FileNotFoundError(f"level0 not found in {pet_dir}. Is this the correct pet directory?")


def find_metadata(pet_dir: Path) -> Path:
    """Find global-metadata.dat in the IL2CPP Metadata directory."""
    candidates = [
        pet_dir / "若叶睦桌宠_Data" / "il2cpp_data" / "Metadata" / "global-metadata.dat",
        pet_dir / "若叶睦桌寵_Data" / "il2cpp_data" / "Metadata" / "global-metadata.dat",
    ]
    for c in candidates:
        if c.is_file():
            return c
    raise FileNotFoundError(
        f"global-metadata.dat not found in {pet_dir}. Is this the correct pet directory?"
    )


def read_api_key_from_registry() -> str | None:
    """Read DeepSeek API key from Windows registry.

    Unity PlayerPrefs appends a hash suffix to value names in the registry
    (e.g. ``DeepSeek_API_Key_h2203339398``), so we enumerate all values and
    match by prefix.
    """
    try:
        key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, REG_PATH)
        i = 0
        while True:
            try:
                name, value, _ = winreg.EnumValue(key, i)
                if name.startswith(REG_KEY):
                    winreg.CloseKey(key)
                    if isinstance(value, bytes):
                        # Some registry entries store as raw bytes
                        return value.decode("utf-8", errors="replace").rstrip("\x00")
                    return str(value).rstrip("\x00")
                i += 1
            except OSError:
                break
        winreg.CloseKey(key)
        return None
    except OSError:
        return None


def find_registry_url_entry() -> tuple[str, object, int] | None:
    """Find the LlmApiUrl_h<hash> PlayerPrefs value, if this pet version has
    one at all. Returns (name, value, reg_type) or None."""
    try:
        key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, REG_PATH)
    except OSError:
        return None
    try:
        i = 0
        while True:
            try:
                name, value, reg_type = winreg.EnumValue(key, i)
            except OSError:
                break
            if name.startswith(REG_URL_KEY) and not name.endswith(REG_BACKUP_SUFFIX):
                return name, value, reg_type
            i += 1
    finally:
        winreg.CloseKey(key)
    return None


def _decode_reg_value(value) -> str:
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="replace").rstrip("\x00")
    return str(value).rstrip("\x00")


def _encode_reg_value(text: str, sample: object) -> object:
    """Encode `text` the same way `sample` was originally stored (raw bytes
    with a trailing NUL, or a plain string) so the game reads it back
    exactly like Unity PlayerPrefs would have written it."""
    if isinstance(sample, bytes):
        return (text + "\x00").encode("utf-8")
    return text


def patch_registry_url(proxy_port: int, log=None) -> bool | None:
    """If this pet version has a dynamic LlmApiUrl PlayerPrefs override
    (present in newer builds, e.g. 1.9.5+, absent in older ones like
    1.9.0), point it at the local proxy and back up the original value
    under a sibling registry name.

    Returns:
        True  — patched
        False — already pointing at the proxy (idempotent no-op)
        None  — this version has no such setting at all — the binary
                patch alone is sufficient there
    """
    if log is None:
        log = print
    found = find_registry_url_entry()
    if found is None:
        log("  [info] 未找到 LlmApiUrl 注册表项 — 该版本不使用动态 URL 覆盖，跳过")
        return None

    name, value, reg_type = found
    current = _decode_reg_value(value)
    proxy_url = f"http://127.0.0.1:{proxy_port}/v1/chat/completions"

    if current == proxy_url:
        log(f"  [info] {name} 已经指向代理 — 跳过")
        return False

    key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, REG_PATH, 0, winreg.KEY_ALL_ACCESS)
    try:
        backup_name = name + REG_BACKUP_SUFFIX
        try:
            winreg.QueryValueEx(key, backup_name)
        except FileNotFoundError:
            winreg.SetValueEx(key, backup_name, 0, reg_type, value)
            log(f"  [OK] 原值已备份到注册表 {backup_name}")

        new_value = _encode_reg_value(proxy_url, value)
        winreg.SetValueEx(key, name, 0, reg_type, new_value)
        log(f"  [OK] {name} 已指向 127.0.0.1:{proxy_port}")
    finally:
        winreg.CloseKey(key)
    return True


def restore_registry_url(log=None) -> None:
    """Restore the LlmApiUrl PlayerPrefs value from its registry backup, if
    one was ever made. No-op on versions that never had this setting."""
    if log is None:
        log = print
    found = find_registry_url_entry()
    if found is None:
        return  # this version never had the setting — nothing to restore

    name, _, _ = found
    backup_name = name + REG_BACKUP_SUFFIX
    try:
        key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, REG_PATH, 0, winreg.KEY_ALL_ACCESS)
    except OSError:
        return
    try:
        try:
            backup_value, backup_type = winreg.QueryValueEx(key, backup_name)
        except FileNotFoundError:
            log(f"  [info] 未找到 {name} 的注册表备份，跳过")
            return
        winreg.SetValueEx(key, name, 0, backup_type, backup_value)
        winreg.DeleteValue(key, backup_name)
        log(f"  [OK] {name} 已从注册表备份还原")
    finally:
        winreg.CloseKey(key)


def patch_file(file_path: Path, check_prefix: bool = True, log=None) -> bool:
    """Replace ALL occurrences of the DeepSeek URL with the proxy URL in-place.

    Args:
        file_path: Path to the binary file to patch.
        check_prefix: If True, verify the 4-byte Unity length prefix before each URL.
                      Set to False for IL2CPP metadata files.
        log: Optional callback for progress messages (defaults to print).

    Returns True if any patches were made, False if already patched.
    """
    if log is None:
        log = print
    data = bytearray(file_path.read_bytes())

    # Replace all occurrences (metadata has multiple)
    count = 0
    search_start = 0
    while True:
        idx = data.find(DEEPSEEK_URL, search_start)
        if idx < 0:
            break

        if check_prefix:
            length_prefix = struct.unpack_from("<I", data, idx - 4)[0]
            if length_prefix != len(DEEPSEEK_URL):
                log(f"  [warn] Length prefix mismatch at 0x{idx:X}: "
                      f"{length_prefix} != {len(DEEPSEEK_URL)}")

        # In-place replacement (same length, safe)
        data[idx:idx + len(PROXY_URL)] = PROXY_URL
        count += 1
        search_start = idx + len(PROXY_URL)

    if count == 0:
        # Already patched?
        if data.find(PROXY_URL) >= 0:
            log(f"  [info] Already patched — skipping")
            return False
        log(f"  [error] DeepSeek URL not found — wrong game version?")
        raise ValueError("URL pattern not found")

    # Atomic write via temp file — avoids pathlib encoding bug on Windows
    # with non-ASCII paths (Path.write_bytes can fail with OSError 22)
    tmp_path = os.path.join(
        os.path.dirname(str(file_path)),
        "_" + os.path.basename(str(file_path)) + ".tmp",
    )
    with open(tmp_path, "wb") as f:
        f.write(data)
    os.replace(tmp_path, str(file_path))
    return True


def uninstall(pet_dir: Path, log=None) -> None:
    """Restore patched game files from their backups and remove every file
    the installer added. Backup files themselves are left in place as a
    second safety net — this only ever restores from them, never deletes
    them."""
    if log is None:
        log = print

    log("正在还原游戏文件...")

    try:
        level0_path = find_level0(pet_dir)
        backup_l0 = pet_dir / "level0.bak"
        if backup_l0.is_file():
            shutil.copy2(backup_l0, level0_path)
            log(f"  [OK] level0 已还原")
        else:
            log(f"  [info] level0 备份不存在，跳过")
    except FileNotFoundError:
        log(f"  [warn] 未找到 level0，跳过")

    try:
        metadata_path = find_metadata(pet_dir)
        backup_meta = metadata_path.parent / "global-metadata.dat.bak"
        if backup_meta.is_file():
            shutil.copy2(backup_meta, metadata_path)
            log(f"  [OK] global-metadata.dat 已还原")
        else:
            log(f"  [info] metadata 备份不存在，跳过")
    except FileNotFoundError:
        pass  # Mono builds never had one to restore

    log("")
    log("正在清理代理文件...")
    for name in ("启动代理.bat", "若叶睦.bat"):
        p = pet_dir / name
        if p.exists():
            p.unlink()
            log(f"  [OK] 已删除: {name}")

    proxy_dir = pet_dir / "roleplay-slim-proxy"
    if proxy_dir.is_dir():
        shutil.rmtree(proxy_dir)
        log(f"  [OK] 已删除: roleplay-slim-proxy\\")

    log("")
    log("正在还原注册表动态 URL 设置（如果有）...")
    restore_registry_url(log=log)

    log("")
    log("还原完成！桌宠已恢复到安装前的状态。")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    print("=" * 60)
    print("  若叶睦桌宠 — roleplay-slim 上下文优化安装工具")
    print("=" * 60)
    print()

    # 0. Determine pet directory
    if len(sys.argv) > 1:
        pet_dir = Path(sys.argv[1]).resolve()
    else:
        # Assume installer is in pet_dir/installer/ or pet_dir/
        script_dir = Path(__file__).resolve().parent
        if (script_dir.parent / "若叶睦桌宠_Data").is_dir():
            pet_dir = script_dir.parent
        elif (script_dir / "若叶睦桌宠_Data").is_dir():
            pet_dir = script_dir
        else:
            pet_dir = Path.cwd()

    print(f"[*] 桌宠目录: {pet_dir}")
    if not pet_dir.is_dir():
        print(f"[错误] 目录不存在: {pet_dir}")
        print("用法: python install.py [桌宠目录路径]")
        sys.exit(1)

    # 1. Find and backup level0 + metadata
    print("\n[1/7] 查找关键文件...")
    try:
        level0_path = find_level0(pet_dir)
        print(f"  [OK] level0: {level0_path}")
    except FileNotFoundError as e:
        print(f"  [错误] {e}")
        sys.exit(1)

    try:
        metadata_path = find_metadata(pet_dir)
        print(f"  [OK] metadata: {metadata_path}")
    except FileNotFoundError as e:
        print(f"  [warn] {e} — 跳过")
        metadata_path = None

    # Backup level0
    backup_l0 = pet_dir / "level0.bak"
    if not backup_l0.exists():
        shutil.copy2(level0_path, backup_l0)
        print(f"  [OK] level0 已备份")
    else:
        print(f"  [info] level0 备份已存在")

    # Backup metadata
    backup_meta = None
    if metadata_path:
        backup_meta = metadata_path.parent / "global-metadata.dat.bak"
        if not backup_meta.exists():
            shutil.copy2(metadata_path, backup_meta)
            print(f"  [OK] metadata 已备份")
        else:
            print(f"  [info] metadata 备份已存在")

    # 2. Read API key from registry
    print("\n[2/6] 读取 API Key...")
    api_key = read_api_key_from_registry()
    if api_key:
        print(f"  [OK] 从注册表读取成功 ({api_key[:8]}...)")
    else:
        print("  [warn] 未在注册表中找到 DeepSeek_API_Key")
        api_key = input("  请手动输入 DeepSeek API Key (sk-...): ").strip()
        if not api_key:
            print("  [错误] API Key 不能为空")
            sys.exit(1)

    # 3. Patch level0
    print(f"\n[3/7] Patch level0 (API 端点 → 代理)...")
    try:
        was_patched = patch_file(level0_path)
        if was_patched:
            print(f"  [OK] level0 已指向 127.0.0.1:{PROXY_PORT}")
    except ValueError:
        print("  [错误] level0 patch 失败! 正在恢复备份...")
        shutil.copy2(backup_l0, level0_path)
        print("  [info] 已从备份恢复")
        sys.exit(1)

    # 4. Patch metadata
    if metadata_path:
        print(f"\n[4/7] Patch global-metadata.dat...")
        try:
            was_patched = patch_file(metadata_path, check_prefix=False)
            if was_patched:
                print(f"  [OK] metadata 已指向 127.0.0.1:{PROXY_PORT}")
        except ValueError:
            print("  [错误] metadata patch 失败! 正在恢复备份...")
            shutil.copy2(backup_meta, metadata_path)
            print("  [info] 已从备份恢复")
            sys.exit(1)
    else:
        print(f"\n[4/7] Patch metadata — 跳过（未找到）")

    # 4.5. Patch dynamic registry URL override (newer builds only, e.g. 1.9.5+)
    print(f"\n[4.5/7] Patch 注册表动态 URL 覆盖设置（如果存在）...")
    patch_registry_url(PROXY_PORT)

    # 5. Write proxy config
    print(f"\n[5/7] 生成代理配置...")
    config_dir = pet_dir / "roleplay-slim-proxy"
    config_dir.mkdir(exist_ok=True)
    config_path = config_dir / "config.toml"
    config_path.write_text(CONFIG_TOML.format(port=PROXY_PORT), encoding="utf-8")
    print(f"  [OK] 配置写入: {config_path}")

    # 6. Write proxy launcher
    print(f"\n[6/7] 创建启动脚本...")
    proxy_bat = pet_dir / "启动代理.bat"
    proxy_bat.write_text(
        LAUNCH_PROXY_BAT.format(api_key=api_key),
        encoding="gbk",
    )
    print(f"  [OK] {proxy_bat}")

    # 7. Write main launcher
    # gbk, matching the default (no chcp) console code page on zh-CN Windows
    # — the file's own encoding has to match whatever code page actually
    # renders it, or our own echo lines show up as mojibake.
    pet_bat = pet_dir / "若叶睦.bat"
    pet_bat.write_text(
        LAUNCH_PET_BAT.replace("{port}", str(PROXY_PORT)),
        encoding="gbk",
    )
    print(f"  [OK] {pet_bat}")

    # Done
    print("\n" + "=" * 60)
    print("  安装完成!")
    print()
    print(f"  以后双击「若叶睦.bat」启动即可")
    print(f"  快捷方式在: {pet_bat}")
    print()
    print(f"  level0 备份: {backup_l0}")
    if backup_meta:
        print(f"  metadata 备份: {backup_meta}")
    print(f"  代理配置:   {config_path}")
    print("=" * 60)
    print()

    # Optional: verify proxy is importable
    try:
        import importlib
        importlib.import_module("roleplay_slim")
        print("[验证] roleplay-slim 库导入成功")
    except ImportError:
        print("[警告] roleplay-slim 未安装，请先运行: pip install \"roleplay-slim[all]\"")
        print("  然后重新运行本安装脚本")


if __name__ == "__main__":
    main()
